### ISSUE TITLE
Extension disables sintax highlighting in documentation on hover popups

### ISSUE THREAD

**Issue by inliquid** [quillaja/goasm#2]
Hi, 
thank you for a very useful extension. 👍  

One problem is that when it's activated syntax highlighting becomes disabled in documentation on hover.

Before
![изображение](https://user-images.githubusercontent.com/6797881/114272157-ab15e500-9a1d-11eb-90d8-a34af0d535ab.png)
After
![изображение](https://user-images.githubusercontent.com/6797881/114272161-b0732f80-9a1d-11eb-9878-b1893fb56ffc.png)

**Comment by quillaja** [comment]
Thanks for opening an issue. I'll look into it. I never really noticed that myself probably because I've had the extension enabled since before there was highlighting in the hovering documentation.

I haven't updated the extension in a long time, so maybe it's using some outdated stuff in vscode's extension api.

**Comment by quillaja** [comment]
I published a fix in v0.0.5. Just something in my package.json that must have conflicted with the go extension. Please check that goasm auto-updated and let me know if that fixed the issue for you.

**Comment by inliquid** [comment]
Yes it's updated and now works fine. Thank you!
